/**********************************************************************************************************************
 * \file Cpu0_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "platform.h"
#include "log.h"

#include "fc/fc_init.h"
#include "scheduler/scheduler.h"

#include "IfxDma_Dma.h"
#include "IfxDma.h"

IfxCpu_syncEvent g_cpuSyncEvent = 0;

uint8_t dmaArray[] = "Hello, World! This data was send using DMA!";
uint8_t dmaTargetArray[100];

#define DMA_CHANNEL_ID      IfxDma_ChannelId_0     /* DMA Channel Id used to transfer data              */

IfxDma_Dma                dmaHandle;                         /* Module handle to HW module SFR set              */
IfxDma_Dma_Config         dmaConfig;                         /* Module configuration structure                  */
IfxDma_Dma_ChannelConfig  dmaChNCfg;                         /* DMA whole channel configurations                */
IfxDma_Dma_Channel        dmaChannel;                        /* DMA channel configuration set                   */

static void initDma(void){
    /* Load default module configuration into configuration structure */
    IfxDma_Dma_initModuleConfig(&dmaConfig, &MODULE_DMA);

    /* Initialize module with configuration. */
    IfxDma_Dma_initModule(&dmaHandle, &dmaConfig);

    /* Get/initialize DMA channel configuration for all DMA channels otherwise use &g_Dma.dmaChannel as target */
    IfxDma_Dma_initChannelConfig(&dmaChNCfg, &dmaHandle);

    /* Set desired DMA channel: Channel 0 is used */
    dmaChNCfg.channelId = DMA_CHANNEL_ID;

    /* Setup the operation mode/settings for DMA channel */
    dmaChNCfg.moveSize = IfxDma_ChannelMoveSize_8bit;
    /* Set the number of DMA transfers */
    dmaChNCfg.transferCount = sizeof(dmaArray);

    /* Execute the DMA transaction with only one trigger */
    dmaChNCfg.requestMode = IfxDma_ChannelRequestMode_completeTransactionPerRequest;

    /* Setup the specific DMA channel configuration */
    IfxDma_Dma_initChannel(&dmaChannel, &dmaChNCfg);
}

/* Trigger a DMA transaction via SW request */
static void triggerDMATransfer(void){
    /* Set destination and source address data to DMA channel */
    dmaChNCfg.sourceAddress      = (uint32_t)&dmaArray[0];
    dmaChNCfg.destinationAddress = (uint32_t)&dmaTargetArray[0];
    IfxDma_Dma_initChannel(&dmaChannel, &dmaChNCfg);

    /* Request start of DMA Transaction channel 0 */
    IfxDma_Dma_startChannelTransaction(&dmaChannel);
}

void core0_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG0 AND SAFETY WATCHDOG ARE DISABLED HERE!!
     * Enable the watchdogs and service them periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    IfxScuWdt_disableSafetyWatchdog(IfxScuWdt_getSafetyWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);

    init();
    initDma();

    LOG_INFO(SYSTEM, "Hello, World! I am running on Aurix.");

    LOG_INFO(SYSTEM, "Entering into scheduler loop");

    //copy data
    triggerDMATransfer();

    //wait until complete
    while(IfxDma_Dma_isChannelTransactionPending(&dmaChannel) == true);

    if(strncmp(&dmaArray[0], &dmaTargetArray[0], sizeof(dmaArray)) == 0){
        LOG_INFO(SYSTEM, "DMA worked.");
    }
    else{
        LOG_ERROR(SYSTEM, "DMA Fail!");
    }

    while(1){
        scheduler();
    }
}
