/**********************************************************************************************************************
 * \file Cpu1_Main.c
 * \copyright Copyright (C) Infineon Technologies AG 2019
 * 
 * Use of this file is subject to the terms of use agreed between (i) you or the company in which ordinary course of 
 * business you are acting and (ii) Infineon Technologies AG or its licensees. If and as long as no such terms of use
 * are agreed, use of this file is subject to following:
 * 
 * Boost Software License - Version 1.0 - August 17th, 2003
 * 
 * Permission is hereby granted, free of charge, to any person or organization obtaining a copy of the software and 
 * accompanying documentation covered by this license (the "Software") to use, reproduce, display, distribute, execute,
 * and transmit the Software, and to prepare derivative works of the Software, and to permit third-parties to whom the
 * Software is furnished to do so, all subject to the following:
 * 
 * The copyright notices in the Software and this entire statement, including the above license grant, this restriction
 * and the following disclaimer, must be included in all copies of the Software, in whole or in part, and all 
 * derivative works of the Software, unless such copies or derivative works are solely in the form of 
 * machine-executable object code generated by a source language processor.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
 * WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE 
 * COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN 
 * CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS 
 * IN THE SOFTWARE.
 *********************************************************************************************************************/
#include "Ifx_Types.h"
#include "IfxCpu.h"
#include "IfxScuWdt.h"

#include "platform.h"

#include "drivers/time.h"
#include "drivers/bus_spi.h"
#include "sensors/gyro.h"
#include "sensors/acceleration.h"

#include "common/log.h"
#include "config.h"

extern IfxCpu_syncEvent g_cpuSyncEvent;
extern IfxCpu_syncEvent g_inavInitComplete;
extern bool g_cpuIsUsed[];

void core1_main(void)
{
    IfxCpu_enableInterrupts();
    
    /* !!WATCHDOG1 IS DISABLED HERE!!
     * Enable the watchdog and service it periodically if it is required
     */
    IfxScuWdt_disableCpuWatchdog(IfxScuWdt_getCpuWatchdogPassword());
    
    /* Wait for CPU sync event */
    IfxCpu_emitEvent(&g_cpuSyncEvent);
    IfxCpu_waitEvent(&g_cpuSyncEvent, 1);
    
#ifdef USE_AURIX_MULTICORE
    //wait until inav init is complete
    IfxCpu_emitEvent(&g_inavInitComplete);
    IfxCpu_waitEvent(&g_inavInitComplete, UINT32_MAX);

    LOG_INFO(SYSTEM, "CPU1 is alive!");
    g_cpuIsUsed[IfxCpu_getCoreIndex()] = true;

    //change the ISR provider of the SPI bus to CPU1
    spiSetHandlingCpu(CPU1_SPI_BUS, IfxCpu_getCoreIndex());

    timeUs_t lastUpdate = 0;
    timeUs_t diff = 0;
    
    while(true) {
        lastUpdate = micros();
        
        if(!gyroUpdate());
        if(!accUpdate());

        diff = micros()-lastUpdate;
        if(diff < TASK_GYRO_LOOPTIME){
            delayMicroseconds(TASK_GYRO_LOOPTIME-diff);
        }
    }
#else
    while(1)
    {
    }
#endif
}
